#!/bin/bash
# setup.sh — interactive first-run wizard for devbrain.
#
# Asks a handful of questions, checks your prerequisites, and writes:
#   - devbrain-projects.allow      (your chosen repos, or an empty templated file)
#   - devbrain.local.env           (gitignored — your Telegram token/chat id)
# Then prints a checklist of manual steps it can't automate.
#
# Safe to re-run: it won't clobber devbrain-projects.allow if you've already
# customized it (asks first), and it always overwrites devbrain.local.env fresh
# since that's meant to be regenerated by this wizard.
set -u
ROOT="$(cd "$(dirname "$0")" && pwd)"
ALLOWFILE="$ROOT/devbrain-projects.allow"
LOCAL_ENV="$ROOT/devbrain.local.env"
REPO_ARR=()

PASS="OK"
FAIL="MISSING"

echo "======================================================================"
echo " devbrain setup"
echo "======================================================================"
echo
echo "This will ask a few questions, check your prerequisites, and write a"
echo "couple of config files. Nothing is sent anywhere — everything stays local."
echo

ask() { # <prompt> -> reads a line into REPLY_VALUE
  local prompt="$1"
  printf '%s' "$prompt"
  IFS= read -r REPLY_VALUE
}

# ----------------------------------------------------------------------------
echo "----------------------------------------------------------------------"
echo "Step 1 of 5 — prerequisites"
echo "----------------------------------------------------------------------"
echo

check() { # <label> <command...> -> prints pass/fail, returns the command's status
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then
    printf '  [%s] %s\n' "$PASS" "$label"
    return 0
  else
    printf '  [%s] %s\n' "$FAIL" "$label"
    return 1
  fi
}

check "git installed" command -v git
GIT_OK=$?
check "python3 installed" command -v python3
PY_OK=$?
check "gh (GitHub CLI) installed" command -v gh
GH_OK=$?
if [ "$GH_OK" -eq 0 ]; then
  check "gh authenticated (gh auth status)" gh auth status
  GH_AUTH_OK=$?
else
  GH_AUTH_OK=1
fi
check "openclaw installed (optional — only if you're using it as the messaging bridge)" command -v openclaw
OPENCLAW_OK=$?

echo
if [ "$GIT_OK" -ne 0 ] || [ "$PY_OK" -ne 0 ]; then
  echo "git and python3 are required for devbrain's scripts to run at all."
  echo "Install them, then re-run this wizard. Continuing anyway so you can"
  echo "still generate config files, but expect things to break until they're fixed."
fi
if [ "$GH_OK" -ne 0 ] || [ "$GH_AUTH_OK" -ne 0 ]; then
  echo "gh (GitHub CLI), authenticated, is required for devbrain to open PRs."
  echo "Install: https://cli.github.com  Then run: gh auth login"
fi
if [ "$OPENCLAW_OK" -ne 0 ]; then
  echo "OpenClaw not found — that's fine if you're using a different messaging"
  echo "bridge, or setting this up later. See README.md for what's swappable."
fi
echo

# ----------------------------------------------------------------------------
echo "----------------------------------------------------------------------"
echo "Step 2 of 5 — your GitHub username"
echo "----------------------------------------------------------------------"
echo
ask "GitHub username: "
GITHUB_USERNAME="$REPLY_VALUE"
if [ -z "$GITHUB_USERNAME" ]; then
  echo "(left blank — some optional tooling, like devbrain-repo-audit, needs this"
  echo " later via the REPO_AUDIT_OWNER environment variable. You can set that"
  echo " whenever you actually use those scripts.)"
fi
echo

# ----------------------------------------------------------------------------
echo "----------------------------------------------------------------------"
echo "Step 3 of 5 — which repos should devbrain manage?"
echo "----------------------------------------------------------------------"
echo
echo "Enter a comma-separated list of repo directory names, exactly as they"
echo "appear under ~/dev/projects/ (e.g. my-website,my-api). Or type 'skip' to"
echo "leave devbrain-projects.allow empty and edit it by hand later."
echo
ask "Repos (comma-separated, or 'skip'): "
REPOS_INPUT="$REPLY_VALUE"
echo

WRITE_ALLOWFILE=1
if [ -f "$ALLOWFILE" ]; then
  # Only overwrite if the file still looks like the untouched template (no
  # uncommented lines) — never clobber a hand-edited allowlist silently.
  if grep -vq '^\s*#' "$ALLOWFILE" 2>/dev/null; then
    echo "devbrain-projects.allow already has uncommented entries — leaving it"
    echo "alone. Edit it by hand if you want to change your repo list."
    WRITE_ALLOWFILE=0
  fi
fi

if [ "$WRITE_ALLOWFILE" -eq 1 ]; then
  {
    echo "# Projects devbrain may plan/execute on. Adding a line here is a"
    echo "# deliberate act by you, the owner."
    echo "#"
    echo "# A repo missing from BOTH this file and devbrain-projects.excluded is"
    echo "# not silently out of scope — devbrain-repo-audit flags it in the daily"
    echo "# digest as unclassified, so you notice and make an explicit decision."
    echo "#"
    echo "# Generated by setup.sh on $(date +%Y-%m-%d)."
  } > "$ALLOWFILE"
  case "$(printf '%s' "$REPOS_INPUT" | tr '[:upper:]' '[:lower:]' | xargs 2>/dev/null)" in
    ''|skip)
      echo "(no repos entered — devbrain-projects.allow left empty; edit it by hand"
      echo " whenever you're ready)"
      ;;
    *)
      IFS=',' read -ra REPO_ARR <<< "$REPOS_INPUT"
      for r in "${REPO_ARR[@]}"; do
        r="$(printf '%s' "$r" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        [ -z "$r" ] && continue
        if ! [[ "$r" =~ ^[A-Za-z0-9_-]+$ ]]; then
          echo "  skipping invalid repo name: '$r' (letters, digits, - and _ only)"
          continue
        fi
        echo "$r" >> "$ALLOWFILE"
        echo "  added: $r"
      done
      ;;
  esac
fi
echo

# ----------------------------------------------------------------------------
echo "----------------------------------------------------------------------"
echo "Step 4 of 5 — which LLM should the Telegram-facing router use?"
echo "----------------------------------------------------------------------"
echo
echo "This is the cheap model that chats with you day-to-day and turns requests"
echo "into devbrain calls or queue entries — NOT the coding agent itself."
echo
echo "  1) Moonshot Kimi (API-based, cheap, good default)"
echo "  2) Local Ollama model (self-hosted, free, needs a running Ollama instance)"
echo "  3) I'll configure this myself"
echo
ask "Choice [1/2/3]: "
LLM_CHOICE="$REPLY_VALUE"
case "$LLM_CHOICE" in
  1)
    LLM_ROUTER="moonshot-kimi"
    echo "Selected: Moonshot Kimi. You'll need an API key from"
    echo "https://platform.moonshot.ai — set it in your messaging bridge's config"
    echo "(e.g. openclaw.json's model provider section), not in this repo."
    ;;
  2)
    LLM_ROUTER="ollama-local"
    echo "Selected: local Ollama. Install from https://ollama.com, pull a model"
    echo "(e.g. 'ollama pull llama3'), and point your messaging bridge's config at"
    echo "http://127.0.0.1:11434."
    ;;
  3)
    LLM_ROUTER="custom"
    echo "Selected: custom. See README.md — this is a config value in your"
    echo "messaging bridge, not something devbrain's own scripts hardcode."
    ;;
  *)
    LLM_ROUTER="unset"
    echo "(no valid choice entered — leaving this for you to configure later)"
    ;;
esac
echo

# ----------------------------------------------------------------------------
echo "----------------------------------------------------------------------"
echo "Step 5 of 5 — Telegram bot token and your chat id"
echo "----------------------------------------------------------------------"
echo
echo "You need two things from Telegram:"
echo "  1. A BOT TOKEN — message @BotFather on Telegram, send /newbot, follow the"
echo "     prompts. It gives you a token that looks like '123456:ABC-def...'."
echo "  2. YOUR numeric chat id — message @userinfobot (or @get_id_bot) on"
echo "     Telegram, it replies with your numeric id."
echo
echo "Both are stored ONLY in a local file ($LOCAL_ENV), which is"
echo "gitignored and never committed. Leave either blank to fill in later by hand."
echo
ask "Telegram bot token (leave blank to skip): "
TG_BOT_TOKEN="$REPLY_VALUE"
ask "Your Telegram numeric chat id (leave blank to skip): "
TG_CHAT_ID="$REPLY_VALUE"
echo

if ! grep -qxF "devbrain.local.env" "$ROOT/.gitignore" 2>/dev/null; then
  echo "devbrain.local.env" >> "$ROOT/.gitignore"
fi

{
  echo "# Generated by setup.sh on $(date +%Y-%m-%d). Local machine config."
  echo "# NEVER commit this file — it is gitignored on purpose."
  echo
  echo "# Your own numeric Telegram chat id (see @userinfobot). Required by"
  echo "# lib/telegram.sh (DEVBRAIN_TG_CHAT_ID) for any script to be able to"
  echo "# message you."
  echo "DEVBRAIN_TG_CHAT_ID=\"${TG_CHAT_ID}\""
  echo
  echo "# Your GitHub username. Two scripts each read their own env var for this"
  echo "# (no shared default, on purpose — see each script's own comments):"
  echo "REPO_AUDIT_OWNER=\"${GITHUB_USERNAME}\"           # bin/devbrain-repo-audit"
  echo "WIKI_STATUS_AUDIT_OWNER=\"${GITHUB_USERNAME}\"    # bin/devbrain-wiki-status-audit"
  echo
  echo "# Which LLM router you picked in setup: moonshot-kimi | ollama-local | custom | unset"
  echo "DEVBRAIN_LLM_ROUTER=\"${LLM_ROUTER}\""
  echo
  echo "# The bot token itself is NOT stored in plain env here by default — put it"
  echo "# in your messaging bridge's own config (e.g. openclaw.json), which is the"
  echo "# thing that actually needs it to call the Telegram API. Uncomment and set"
  echo "# it here too only if some script you wrote yourself needs to read it from"
  echo "# this file directly."
  if [ -n "$TG_BOT_TOKEN" ]; then
    echo "# TELEGRAM_BOT_TOKEN=\"${TG_BOT_TOKEN}\""
  else
    echo "# TELEGRAM_BOT_TOKEN=\"\""
  fi
} > "$LOCAL_ENV"
chmod 600 "$LOCAL_ENV"
echo "Wrote $LOCAL_ENV (mode 600, gitignored)."
echo

# ----------------------------------------------------------------------------
echo "----------------------------------------------------------------------"
echo "Generating what we can automate — no more copy-pasting paths by hand"
echo "----------------------------------------------------------------------"
echo

# exec-approvals.json only needs the one path this wizard already knows.
EXEC_APPROVALS="$ROOT/openclaw/exec-approvals.json"
if [ -f "$EXEC_APPROVALS" ] && grep -q "ABSOLUTE/PATH/TO/YOUR/CLONE/OF/THIS/REPO" "$EXEC_APPROVALS"; then
  sed -i.bak "s#/ABSOLUTE/PATH/TO/YOUR/CLONE/OF/THIS/REPO#${ROOT}#g" "$EXEC_APPROVALS"
  rm -f "${EXEC_APPROVALS}.bak"
  echo "  [ok] patched openclaw/exec-approvals.json with $ROOT"
else
  echo "  [skip] openclaw/exec-approvals.json already customized (or missing)"
fi

# The house-rules file devbrain reads (bin/devbrain's own default) — never
# touched if it already exists, since it's meant to be yours.
HOUSE_RULES="${DEVBRAIN_HOUSE_RULES:-$HOME/dev/CLAUDE.md}"
if [ ! -f "$HOUSE_RULES" ]; then
  mkdir -p "$(dirname "$HOUSE_RULES")"
  {
    echo "# CLAUDE.md — house rules"
    echo
    echo "Generated by setup.sh on $(date +%Y-%m-%d) as a starting stub — devbrain works"
    echo "fine against an empty house-rules file, but you should fill this in with"
    echo "your own standards. See this repo's README.md for what other scripts assume"
    echo "is in here."
    echo
    echo "## Workflow — propose-only"
    echo
    echo "1. Plan first. Wait for explicit approval before touching code."
    echo "2. Work on a feature branch, never on main. Never push to main."
    echo "3. Finish with a PR (what changed, why, risks, how to verify). Never merge —"
    echo "   you merge from the GitHub app."
    echo
    echo "## Hard limits"
    echo
    echo "- Never deploy to production."
    echo "- Never write to real business/user data in an unattended session."
    echo "- Never merge PRs, force-push, or delete branches it didn't create."
    if [ "${#REPO_ARR[@]}" -gt 0 ]; then
      echo
      echo "## Repos"
      echo
      for r in "${REPO_ARR[@]}"; do
        echo "- $r"
      done
    fi
  } > "$HOUSE_RULES"
  echo "  [ok] wrote $HOUSE_RULES (didn't exist yet — it's a stub, flesh it out)"
else
  echo "  [skip] $HOUSE_RULES already exists — leaving it alone"
fi

# launchd jobs — macOS only. Written, never loaded: loading them is the one
# step that actually starts unattended runs, so that stays a decision you make.
LAUNCHD_GENERATED=0
if [ "$(uname -s)" = "Darwin" ]; then
  LAUNCHD_DIR="$HOME/Library/LaunchAgents"
  mkdir -p "$LAUNCHD_DIR"
  write_plist() { # <label-suffix> <bin-name> <schedule-xml>
    local suffix="$1" bin="$2" schedule="$3"
    local plist="$LAUNCHD_DIR/com.devbrain.${suffix}.plist"
    if [ -f "$plist" ]; then
      echo "  [skip] $plist already exists"
      return
    fi
    cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.devbrain.${suffix}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${ROOT}/bin/${bin}</string>
  </array>
  <key>WorkingDirectory</key><string>${ROOT}</string>
  <key>StandardOutPath</key><string>${HOME}/Library/Logs/devbrain-${suffix}.log</string>
  <key>StandardErrorPath</key><string>${HOME}/Library/Logs/devbrain-${suffix}.log</string>
${schedule}
</dict>
</plist>
PLIST
    echo "  [ok] wrote $plist"
  }
  write_plist "night" "devbrain-night" '  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>23</integer><key>Minute</key><integer>0</integer></dict>'
  write_plist "digest" "devbrain-digest" '  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>6</integer><key>Minute</key><integer>0</integer></dict>'
  write_plist "heartbeat" "devbrain-heartbeat" '  <key>StartInterval</key>
  <integer>300</integer>'
  LAUNCHD_GENERATED=1
else
  echo "  [skip] not macOS — launchd doesn't apply; use cron/systemd (see README.md)"
fi

# claude/skills/ -> ~/.claude/skills/ is exactly what this script already does,
# idempotently — just run it instead of telling you to.
if [ -x "$ROOT/bin/install-claude-skills" ]; then
  "$ROOT/bin/install-claude-skills"
else
  echo "  [skip] bin/install-claude-skills not found or not executable"
fi
echo

# ----------------------------------------------------------------------------
echo "======================================================================"
echo " Done with what setup.sh can automate. Manual steps left:"
echo "======================================================================"
echo
echo "  [ ] source devbrain.local.env (or export DEVBRAIN_TG_CHAT_ID and"
echo "      REPO_AUDIT_OWNER some other way) before running devbrain's scripts."
[ "$GH_AUTH_OK" -ne 0 ] && echo "  [ ] run: gh auth login"
[ "$OPENCLAW_OK" -ne 0 ] && echo "  [ ] install OpenClaw (or your chosen messaging bridge) and configure its"
[ "$OPENCLAW_OK" -ne 0 ] && echo "      Telegram bot token — see https://github.com/openclaw/openclaw"
echo "  [ ] copy openclaw/workspace/*.md into your bridge's workspace and fill in"
echo "      the <PLACEHOLDER> markers (your name, repo names, assistant persona)"
if [ "$LAUNCHD_GENERATED" -eq 1 ]; then
  echo "  [ ] review the generated jobs in ~/Library/LaunchAgents/com.devbrain.*.plist,"
  echo "      then load each one you want running:"
  echo "        launchctl load ~/Library/LaunchAgents/com.devbrain.night.plist"
  echo "        launchctl load ~/Library/LaunchAgents/com.devbrain.digest.plist"
  echo "        launchctl load ~/Library/LaunchAgents/com.devbrain.heartbeat.plist"
fi
echo "  [ ] review devbrain-projects.allow, devbrain-projects.excluded,"
echo "      devbrain-base-branch.override, devbrain-verify.commands, and"
echo "      devbrain-migration-block.list — all ship mostly empty/commented, by"
echo "      design, so you opt in to each safeguard on purpose"
echo "  [ ] flesh out $HOUSE_RULES with your own standards and tone"
echo "  [ ] run the test suite: for f in tests/*.sh; do bash \"\$f\" || echo \"FAILED: \$f\"; done"
echo
echo "See README.md for the full architecture and what's swappable."
